import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Notification from '@/components/Notification'
import Footer from '@/components/Footer'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Notification/>
        <Navbar/>  
        {children}
        <Footer/>
      </body>
    </html>
  )
}
// Creamos los layout para que se puedan ver en todas las paginas...
// A su vez implementamos que el footer obviamente vaya debajo del children ya que es el final de la pagina